jobs:
  include:
    - language: cpp
      dist: bionic
      env:
        - GMODNET_VERSION="0.4.0"
      script:
        - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo add-apt-repository universe
        - sudo apt-get update
        - sudo apt-get install apt-transport-https
        - sudo apt-get update
        - sudo apt-get install dotnet-sdk-3.0
        - dotnet publish gm_dotnet_managed/GmodNET.API/GmodNET.API.csproj -c Release 
        - dotnet publish gm_dotnet_managed/GmodNET/GmodNET.csproj -c Release
        - mkdir cmake_build
        - cd cmake_build
        - cmake ../gm_dotnet_native
        - make
        - cd ..
        - mkdir build
        - mkdir build/GmodNET
        - mkdir build/GmodNET/API
        - cp cmake_build/*.dll build
        - cp gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.0/publish/*.dll build/GmodNET
        - cp gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.0/publish/*.json build/GmodNET
        - mkdir build/GmodNET/runtimes
        - cp -r gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.0/publish/runtimes/* build/GmodNET/runtimes
        - cp gm_dotnet_managed/GmodNET.API/bin/Release/netcoreapp3.0/GmodNET.API.dll build/GmodNET/API
        - cd build 
        - mkdir dotnet
        - cd dotnet
        - wget https://download.visualstudio.microsoft.com/download/pr/a5ff9cbb-d558-49d1-9fd2-410cb1c8b095/a940644f4133b81446cb3733a620983a/dotnet-runtime-3.0.0-linux-x64.tar.gz
        - tar xvf dotnet-runtime-3.0.0-linux-x64.tar.gz
        - rm -f dotnet-runtime-3.0.0-linux-x64.tar.gz
        - rm -f dotnet
        - rm -f LICENSE.rxt
        - rm -f ThirdPartyNotices.txt
        - cd ..
        - cd ..
        - cp LICENSE build
        - cp NOTICE build        
        - git clone https://GlebChili:$GITHUB_TOKEN@github.com/GlebChili/GmodDotNetPrivateKey.git
        - wget https://github.com/GlebChili/GmodNetModuleSigner/releases/download/1.0.0/gms
        - chmod +x gms
        - cd build
        - ./../gms --sign=gmcl_dotent_linux64.dll --key=../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign gmcl_dotent.modulesign
        - cp ../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey gmcl_dotnet.modulekey
        - cd GmodNET
        - ./../../gms --sign=GmodNET.dll --key=../../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign GmodNET.modulesign
        - cp ../../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey GmodNET.modulekey
        - cd ..
        - tar czfv ../$TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz .
        - cd ..
        - mkdir files_to_publish
        - cp $TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz files_to_publish
      deploy:
        provider: s3
        access_key_id: $SPACE_ID
        secret_access_key: $SPACE_KEY
        bucket: gleb-krasilich
        skip_cleanup: true
        upload-dir: GmodDotNetBuilds/Linux/$TRAVIS_BRANCH
        local_dir: files_to_publish
        acl: public_read
        on:
          all_branches: true
        endpoint: https://fra1.digitaloceanspaces.com
    
    - language: cpp
      os: windows
      env:
        - GMODNET_VERSION=0.4.0
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - choco install dotnetcore-sdk --version 3.0.100
        - dotnet publish gm_dotnet_managed/GmodNET.API/GmodNET.API.csproj -c Release 
        - dotnet publish gm_dotnet_managed/GmodNET/GmodNET.csproj -c Release
        - mkdir cmake_build
        - cd cmake_build
        - cmake -G 'Visual Studio 15 2017 Win64' ../gm_dotnet_native
        - export PATH=$MSBUILD_PATH:$PATH
        - msbuild.exe gm_dotnet_native.sln
        - cd ..
        - mkdir build
        - mkdir build/GmodNET
        - mkdir build/GmodNET/API
        - cp cmake_build/Release/*.dll build
        - cp gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.0/publish/*.dll build/GmodNET
        - cp gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.0/publish/*.json build/GmodNET
        - mkdir build/GmodNET/runtimes
        - cp -r gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.0/publish/runtimes/* build/GmodNET/runtimes
        - cp gm_dotnet_managed/GmodNET.API/bin/Release/netcoreapp3.0/GmodNET.API.dll build/GmodNET/API
        - export NOW=$( date '+%F_%H_%M_%S' )
        - 7z a -tzip $NOW-$TRAVIS_BRANCH-$TRAVIS_COMMIT.zip build
        - mkdir files_to_publish
        - cp $NOW-$TRAVIS_BRANCH-$TRAVIS_COMMIT.zip files_to_publish
      deploy:
        provider: s3
        edge: true
        access_key_id: $SPACE_ID
        secret_access_key: $SPACE_KEY
        bucket: gleb-krasilich
        skip_cleanup: true
        upload-dir: GmodDotNetBuilds/Windows
        local_dir: files_to_publish
        acl: public_read
        on:
          all_branches: true
        endpoint: https://fra1.digitaloceanspaces.com
      
        
        
        
