env:
  - GMODNET_VERSION="0.5.0"

stages:
  - build
  - tests

jobs:
  include:
    - language: cpp
      stage: build
      dist: bionic
      name: Linux builder
      script:
        - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo add-apt-repository universe
        - sudo apt-get update
        - sudo apt-get install apt-transport-https
        - sudo apt-get update
        - sudo apt-get install dotnet-sdk-3.1
        - dotnet publish gm_dotnet_managed/GmodNET.API/GmodNET.API.csproj -c Release 
        - dotnet publish gm_dotnet_managed/GmodNET/GmodNET.csproj -c Release
        - mkdir cmake_build
        - cd cmake_build
        - cmake ../gm_dotnet_native
        - make
        - cd ..
        - mkdir build
        - mkdir build/GmodNET
        - mkdir build/GmodNET/API
        - cp cmake_build/*.dll build
        - cp -a -v gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.1/publish/. build/GmodNET
        - cp gm_dotnet_managed/GmodNET.API/bin/Release/netcoreapp3.1/GmodNET.API.dll build/GmodNET/API
        - find build/GmodNET/*.exe | xargs rm -f -v
        - find build/GmodNET/*.pdb | xargs rm -f -v
        - rm -f -v build/GmodNET/GmodNET
        - rm -f -v build/GmodNET/web.config
        - cd build 
        - mkdir dotnet
        - cd dotnet
        - wget https://download.visualstudio.microsoft.com/download/pr/30915c37-fa5a-4930-b4e6-b4130e4596b2/38d531c10dc56950f17f3c604e9a2ebc/aspnetcore-runtime-3.1.0-linux-x64.tar.gz
        - tar xvf aspnetcore-runtime-3.1.0-linux-x64.tar.gz
        - rm -f -v aspnetcore-runtime-3.1.0-linux-x64.tar.gz
        - rm -f -v dotnet
        - rm -f -v LICENSE.txt
        - rm -f -v ThirdPartyNotices.txt
        - cd ..
        - cd ..
        - cp LICENSE build
        - cp NOTICE build        
        - git clone https://GlebChili:$GITHUB_TOKEN@github.com/GlebChili/GmodDotNetPrivateKey.git
        - wget https://github.com/GlebChili/GmodNetModuleSigner/releases/download/1.0.0/gms
        - chmod +x gms
        - cd build
        - ./../gms --sign=gmcl_dotnet_linux64.dll --key=../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign gmcl_dotnet.modulesign
        - cp ../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey gmcl_dotnet.modulekey
        - cd GmodNET
        - ./../../gms --sign=GmodNET.dll --key=../../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign GmodNET.modulesign
        - cp ../../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey GmodNET.modulekey
        - cd ..
        - tar czfv ../$TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz .
        - cd ..
        - mkdir files_to_publish
        - cp $TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz files_to_publish
      deploy:
        provider: s3
        access_key_id: $SPACE_ID
        secret_access_key: $SPACE_KEY
        bucket: gleb-krasilich
        skip_cleanup: true
        upload-dir: GmodDotNetBuilds/Linux/$TRAVIS_BRANCH
        local_dir: files_to_publish
        acl: public_read
        on:
          all_branches: true
        endpoint: https://fra1.digitaloceanspaces.com
    
    - language: cpp
      stage: build
      os: windows
      name: Windows builder
      script:
        - export MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
        - choco install dotnetcore-sdk --version 3.1.100
        - dotnet publish gm_dotnet_managed/GmodNET.API/GmodNET.API.csproj -c Release 
        - dotnet publish gm_dotnet_managed/GmodNET/GmodNET.csproj -c Release
        - mkdir cmake_build
        - cd cmake_build
        - cmake -G 'Visual Studio 15 2017 Win64' ../gm_dotnet_native
        - export PATH=$MSBUILD_PATH:$PATH
        - msbuild.exe gm_dotnet_native.sln
        - cd ..
        - mkdir build
        - mkdir build/GmodNET
        - mkdir build/GmodNET/API
        - cp cmake_build/Release/*.dll build
        - cp -a -v gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.1/publish/. build/GmodNET
        - cp gm_dotnet_managed/GmodNET.API/bin/Release/netcoreapp3.1/GmodNET.API.dll build/GmodNET/API
        - find build/GmodNET/*.exe | xargs rm -f -v
        - find build/GmodNET/*.pdb | xargs rm -f -v
        - rm -f -v build/GmodNET/web.config
        - cd build
        - mkdir dotnet
        - cd dotnet
        - curl https://download.visualstudio.microsoft.com/download/pr/33fb1832-334a-4b72-ae47-ff9d07722cbd/f0b492014f4f5659a57c0f5f42913152/aspnetcore-runtime-3.1.0-win-x64.zip -O -L
        - 7z x -tzip aspnetcore-runtime-3.1.0-win-x64.zip
        - rm -f aspnetcore-runtime-3.1.0-win-x64.zip
        - rm -f dotnet
        - rm -f LICENSE.txt
        - rm -f ThirdPartyNotices.txt
        - cd ..
        - cd ..
        - cp LICENSE build
        - cp NOTICE build
        - git clone https://GlebChili:$GITHUB_TOKEN@github.com/GlebChili/GmodDotNetPrivateKey.git
        - curl https://github.com/GlebChili/GmodNetModuleSigner/releases/download/1.0.0/gms.exe -O -L
        - cd build
        - ./../gms --sign=gmcl_dotnet_win64.dll --key=../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign gmcl_dotnet.modulesign
        - cp ../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey gmcl_dotnet.modulekey
        - cd GmodNET
        - ./../../gms --sign=GmodNET.dll --key=../../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign GmodNET.modulesign
        - cp ../../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey GmodNET.modulekey
        - cd ../..
        - 7z a -tzip $TRAVIS_BRANCH-$TRAVIS_COMMIT.zip ./build/*
        - mkdir files_to_publish
        - cp $TRAVIS_BRANCH-$TRAVIS_COMMIT.zip files_to_publish
      deploy:
        provider: s3
        edge: true
        access_key_id: $SPACE_ID
        secret_access_key: $SPACE_KEY
        bucket: gleb-krasilich
        skip_cleanup: true
        upload-dir: GmodDotNetBuilds/Windows/$TRAVIS_BRANCH
        local_dir: files_to_publish
        acl: public_read
        on:
          all_branches: true
        endpoint: https://fra1.digitaloceanspaces.com
    
    - language: cpp
      stage: build
      os: osx
      name: Mac builder
      script:
        - curl https://dotnetwebsite.azurewebsites.net/download/dotnet-core/scripts/v1/dotnet-install.sh -O -L
        - chmod +x dotnet-install.sh
        - mkdir dnsdk
        - ./dotnet-install.sh --version 3.1.100 --install-dir dnsdk
        - ./dnsdk/dotnet publish gm_dotnet_managed/GmodNET.API/GmodNET.API.csproj -c Release 
        - ./dnsdk/dotnet publish gm_dotnet_managed/GmodNET/GmodNET.csproj -c Release
        - mkdir cmake_build
        - cd cmake_build
        - cmake ../gm_dotnet_native
        - make
        - cd ..
        - mkdir build
        - mkdir build/GmodNET
        - mkdir build/GmodNET/API
        - cp cmake_build/*.dll build
        - cp -a -v gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.1/publish/. build/GmodNET
        - cp gm_dotnet_managed/GmodNET.API/bin/Release/netcoreapp3.1/GmodNET.API.dll build/GmodNET/API
        - find build/GmodNET/*.exe | xargs rm -f -v
        - find build/GmodNET/*.pdb | xargs rm -f -v
        - rm -f -v build/GmodNET/GmodNET
        - rm -f -v build/GmodNET/web.config
        - cd build 
        - mkdir dotnet
        - cd dotnet
        - curl https://download.visualstudio.microsoft.com/download/pr/16106b5c-2dd0-429b-ac74-79c7d47fc575/cb9f53870983845f81b740b27d412038/aspnetcore-runtime-3.1.0-osx-x64.tar.gz -O -L
        - tar xvf aspnetcore-runtime-3.1.0-osx-x64.tar.gz
        - rm -f -v aspnetcore-runtime-3.1.0-osx-x64.tar.gz
        - rm -f dotnet
        - rm -f LICENSE.txt
        - rm -f ThirdPartyNotices.txt
        - cd ..
        - cd ..
        - cp LICENSE build
        - cp NOTICE build        
        - git clone https://GlebChili:$GITHUB_TOKEN@github.com/GlebChili/GmodDotNetPrivateKey.git
        - curl https://github.com/GlebChili/GmodNetModuleSigner/releases/download/1.0.0/gms-osx -O -L
        - mv gms-osx gms
        - chmod +x gms
        - cd build
        - ./../gms --sign=gmcl_dotnet_osx64.dll --key=../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign gmcl_dotnet.modulesign
        - cp ../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey gmcl_dotnet.modulekey
        - cd GmodNET
        - ./../../gms --sign=GmodNET.dll --key=../../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign GmodNET.modulesign
        - cp ../../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey GmodNET.modulekey
        - cd ..
        - tar czfv ../$TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz .
        - cd ..
        - mkdir files_to_publish
        - cp $TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz files_to_publish
      deploy:
        provider: s3
        access_key_id: $SPACE_ID
        secret_access_key: $SPACE_KEY
        bucket: gleb-krasilich
        skip_cleanup: true
        upload-dir: GmodDotNetBuilds/Osx/$TRAVIS_BRANCH
        local_dir: files_to_publish
        acl: public_read
        on:
          all_branches: true
        endpoint: https://fra1.digitaloceanspaces.com
        
    - language: minimal
      stage: build
      name: Lua assembler
      script: 
        - mkdir folder_to_deploy
        - cp lua/autorun/clientside/gm_dotnet_client.lua folder_to_deploy
        - cp lua/autorun/serverside/gm_dotnet_server.lua folder_to_deploy
      deploy:
        provider: s3
        access_key_id: $SPACE_ID
        secret_access_key: $SPACE_KEY
        bucket: gleb-krasilich
        skip_cleanup: true
        upload-dir: GmodDotNetBuilds/Lua/$TRAVIS_BRANCH/$TRAVIS_COMMIT
        local_dir: folder_to_deploy
        acl: public_read
        on:
          all_branches: true
        endpoint: https://fra1.digitaloceanspaces.com
    
    - language: node_js
      node_js:
        - 12
      stage: tests
      name: Discord notifier
      script:
        - cd node
        - npm update
        - node discord.js $WEBHOOK_URL $TRAVIS_BRANCH $TRAVIS_COMMIT
        
        
        
      
      
        