jobs:
  include:
    - language: cpp
      dist: bionic
      script:
        - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo add-apt-repository universe
        - sudo apt-get update
        - sudo apt-get install apt-transport-https
        - sudo apt-get update
        - sudo apt-get install dotnet-sdk-3.0
        - dotnet publish gm_dotnet_managed/GmodNET.API/GmodNET.API.csproj -c Release 
        - dotnet publish gm_dotnet_managed/GmodNET/GmodNET.csproj -c Release
        - mkdir cmake_build
        - cd cmake_build
        - cmake ../gm_dotnet_native
        - make
        - cd ..
        - mkdir build
        - mkdir build/GmodNET
        - mkdir build/GmodNET/API
        - cp cmake_build/*.dll build
        - cp gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.0/publish/*.dll build/GmodNET
        - cp gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.0/publish/*.json build/GmodNET
        - mkdir build/GmodNET/runtimes
        - cp -r gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.0/publish/runtimes/* build/GmodNET/runtimes
        - cp gm_dotnet_managed/GmodNET.API/bin/Release/netcoreapp3.0/GmodNET.API.dll build/GmodNET/API
        - export NOW=$( date '+%F_%H_%M_%S' )
        - tar czf $NOW-$TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz build
        - mkdir files_to_publish
        - cp $NOW-$TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz files_to_publish
        - dir
      deploy:
        provider: s3
        access_key_id: $SPACE_ID
        secret_access_key: $SPACE_KEY
        bucket: gleb-krasilich
        skip_cleanup: true
        upload-dir: GmodDotNetBuilds/Linux
        local_dir: files_to_publish
        acl: public_read
        on:
          all_branches: true
        endpoint: https://fra1.digitaloceanspaces.com
        
