jobs:
  include:
    - language: cpp
      dist: bionic
      script:
        - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        - dpkg -i packages-microsoft-prod.deb
        - add-apt-repository universe
        - apt-get update
        - apt-get install apt-transport-https
        - apt-get update
        - apt-get install dotnet-sdk-3.0
        - dotnet publish gm_dotnet_managed/GmodNET.API/GmodNET.API.csproj -c Release 
        - dotnet publish gm_dotnet_managed/GmodNET/GmodNET.csproj -c Release -r linux-x64
    
