env:
  - GMODNET_VERSION="0.6.0"

stages:
  - build
  - tests
  - notification

jobs:
  include:
    - language: cpp
      stage: build
      dist: bionic
      name: Linux builder
      script:
        - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo add-apt-repository universe
        - sudo apt-get update
        - sudo apt-get install apt-transport-https
        - sudo apt-get update
        - sudo apt-get install dotnet-sdk-3.1
        - dotnet publish gm_dotnet_managed/GmodNET.API/GmodNET.API.csproj -c Release
        - dotnet publish gm_dotnet_managed/GmodNET/GmodNET.csproj -c Release
        - mkdir cmake_build
        - cd cmake_build
        - cmake ../gm_dotnet_native
        - make
        - cd ..
        - mkdir build
        - mkdir build/gmodnet
        - mkdir build/gmodnet/API
        - cp cmake_build/*.dll build
        - cp -a -v gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.1/publish/. build/gmodnet
        - cp gm_dotnet_managed/GmodNET.API/bin/Release/netcoreapp3.1/GmodNET.API.dll build/gmodnet/API
        - find build/gmodnet/*.exe | xargs rm -f -v
        - find build/gmodnet/*.pdb | xargs rm -f -v
        - rm -f -v build/gmodnet/GmodNET
        - rm -f -v build/gmodnet/web.config
        - cd build
        - mkdir dotnet
        - cd dotnet
        - wget https://download.visualstudio.microsoft.com/download/pr/deeee432-fd3c-4dbc-bc06-cbf166cbcfb7/04747ae7a0ea63e01b6f932cccdcf837/aspnetcore-runtime-3.1.1-linux-x64.tar.gz
        - tar xvf aspnetcore-runtime-3.1.1-linux-x64.tar.gz
        - rm -f -v aspnetcore-runtime-3.1.1-linux-x64.tar.gz
        - rm -f -v dotnet
        - rm -f -v LICENSE.txt
        - rm -f -v ThirdPartyNotices.txt
        - cd ..
        - cd ..
        - cp LICENSE build
        - cp NOTICE build
        - git clone https://GlebChili:$GITHUB_TOKEN@github.com/GlebChili/GmodDotNetPrivateKey.git
        - wget https://github.com/GlebChili/GmodNetModuleSigner/releases/download/1.0.0/gms
        - chmod +x gms
        - cd build
        - ./../gms --sign=gmcl_dotnet_linux64.dll --key=../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign gmcl_dotnet.modulesign
        - cp ../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey gmcl_dotnet.modulekey
        - cd gmodnet
        - ./../../gms --sign=GmodNET.dll --key=../../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign GmodNET.modulesign
        - cp ../../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey GmodNET.modulekey
        - cd ..
        - tar czfv ../$TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz .
        - cd ..
        - mkdir files_to_publish
        - cp $TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz files_to_publish
      deploy:
        provider: s3
        access_key_id: $SPACE_ID
        secret_access_key: $SPACE_KEY
        bucket: gleb-krasilich
        skip_cleanup: true
        upload-dir: GmodDotNetBuilds/Linux/$TRAVIS_BRANCH
        local_dir: files_to_publish
        acl: public_read
        on:
          all_branches: true
        endpoint: https://fra1.digitaloceanspaces.com

    - language: cpp
      stage: build
      os: windows
      name: Windows builder
      script:
        - export MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
        - curl https://dotnetwebsite.azurewebsites.net/download/dotnet-core/scripts/v1/dotnet-install.ps1 -O -L
        - mkdir ./netcore
        - powershell -Command Set-ExecutionPolicy -Scope CurrentUser Unrestricted
        - powershell -File ./dotnet-install.ps1 -Version 3.1.101 -InstallDir ./netcore
        - ./netcore/dotnet.exe publish gm_dotnet_managed/GmodNET.API/GmodNET.API.csproj -c Release
        - ./netcore/dotnet.exe publish gm_dotnet_managed/GmodNET/GmodNET.csproj -c Release
        - mkdir cmake_build
        - cd cmake_build
        - cmake -G 'Visual Studio 15 2017 Win64' ../gm_dotnet_native
        - export PATH=$MSBUILD_PATH:$PATH
        - msbuild.exe gm_dotnet_native.sln
        - cd ..
        - mkdir build
        - mkdir build/gmodnet
        - mkdir build/gmodnet/API
        - cp cmake_build/Release/*.dll build
        - cp -a -v gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.1/publish/. build/gmodnet
        - cp gm_dotnet_managed/GmodNET.API/bin/Release/netcoreapp3.1/GmodNET.API.dll build/gmodnet/API
        - find build/gmodnet/*.exe | xargs rm -f -v
        - find build/gmodnet/*.pdb | xargs rm -f -v
        - rm -f -v build/gmodnet/web.config
        - cd build
        - mkdir dotnet
        - cd dotnet
        - curl https://download.visualstudio.microsoft.com/download/pr/5db5952d-a6d6-4b48-b9a8-a3f52fb62a9c/80217ca86ef3894db2f8d63bed413b70/aspnetcore-runtime-3.1.1-win-x64.zip -O -L
        - 7z x -tzip aspnetcore-runtime-3.1.1-win-x64.zip
        - rm -f aspnetcore-runtime-3.1.1-win-x64.zip
        - rm -f dotnet
        - rm -f LICENSE.txt
        - rm -f ThirdPartyNotices.txt
        - cd ..
        - cd ..
        - cp LICENSE build
        - cp NOTICE build
        - git clone https://GlebChili:$GITHUB_TOKEN@github.com/GlebChili/GmodDotNetPrivateKey.git
        - curl https://github.com/GlebChili/GmodNetModuleSigner/releases/download/1.0.0/gms.exe -O -L
        - cd build
        - ./../gms --sign=gmcl_dotnet_win64.dll --key=../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign gmcl_dotnet.modulesign
        - cp ../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey gmcl_dotnet.modulekey
        - cd gmodnet
        - ./../../gms --sign=GmodNET.dll --key=../../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign GmodNET.modulesign
        - cp ../../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey GmodNET.modulekey
        - cd ../..
        - 7z a -tzip $TRAVIS_BRANCH-$TRAVIS_COMMIT.zip ./build/*
        - mkdir files_to_publish
        - cp $TRAVIS_BRANCH-$TRAVIS_COMMIT.zip files_to_publish
      deploy:
        provider: s3
        edge: true
        access_key_id: $SPACE_ID
        secret_access_key: $SPACE_KEY
        bucket: gleb-krasilich
        skip_cleanup: true
        upload-dir: GmodDotNetBuilds/Windows/$TRAVIS_BRANCH
        local_dir: files_to_publish
        acl: public_read
        on:
          all_branches: true
        endpoint: https://fra1.digitaloceanspaces.com

    - language: cpp
      stage: build
      os: osx
      name: Mac builder
      script:
        - curl https://dotnetwebsite.azurewebsites.net/download/dotnet-core/scripts/v1/dotnet-install.sh -O -L
        - chmod +x dotnet-install.sh
        - mkdir dnsdk
        - ./dotnet-install.sh --version 3.1.101 --install-dir dnsdk
        - ./dnsdk/dotnet publish gm_dotnet_managed/GmodNET.API/GmodNET.API.csproj -c Release
        - ./dnsdk/dotnet publish gm_dotnet_managed/GmodNET/GmodNET.csproj -c Release
        - mkdir cmake_build
        - cd cmake_build
        - cmake ../gm_dotnet_native
        - make
        - cd ..
        - mkdir build
        - mkdir build/gmodnet
        - mkdir build/gmodnet/API
        - cp cmake_build/*.dll build
        - cp -a -v gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.1/publish/. build/gmodnet
        - cp gm_dotnet_managed/GmodNET.API/bin/Release/netcoreapp3.1/GmodNET.API.dll build/gmodnet/API
        - find build/gmodnet/*.exe | xargs rm -f -v
        - find build/gmodnet/*.pdb | xargs rm -f -v
        - rm -f -v build/gmodnet/GmodNET
        - rm -f -v build/gmodnet/web.config
        - cd build
        - mkdir dotnet
        - cd dotnet
        - curl https://download.visualstudio.microsoft.com/download/pr/eaa2315e-a8df-45dc-9cb1-68829fbf1255/715d7b13a5fa0b9ad5f00ce8132bee0d/aspnetcore-runtime-3.1.1-osx-x64.tar.gz -O -L
        - tar xvf aspnetcore-runtime-3.1.1-osx-x64.tar.gz
        - rm -f -v aspnetcore-runtime-3.1.1-osx-x64.tar.gz
        - rm -f dotnet
        - rm -f LICENSE.txt
        - rm -f ThirdPartyNotices.txt
        - cd ..
        - cd ..
        - cp LICENSE build
        - cp NOTICE build
        - git clone https://GlebChili:$GITHUB_TOKEN@github.com/GlebChili/GmodDotNetPrivateKey.git
        - curl https://github.com/GlebChili/GmodNetModuleSigner/releases/download/1.0.0/gms-osx -O -L
        - mv gms-osx gms
        - chmod +x gms
        - cd build
        - ./../gms --sign=gmcl_dotnet_osx64.dll --key=../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign gmcl_dotnet.modulesign
        - cp ../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey gmcl_dotnet.modulekey
        - cd gmodnet
        - ./../../gms --sign=GmodNET.dll --key=../../GmodDotNetPrivateKey/gmodnet-private.modulekey --version=$GMODNET_VERSION
        - mv signature.modulesign GmodNET.modulesign
        - cp ../../GmodDotNetPrivateKey/gmodnet-public.modulekey .
        - mv gmodnet-public.modulekey GmodNET.modulekey
        - cd ..
        - tar czfv ../$TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz .
        - cd ..
        - mkdir files_to_publish
        - cp $TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz files_to_publish
      deploy:
        provider: s3
        access_key_id: $SPACE_ID
        secret_access_key: $SPACE_KEY
        bucket: gleb-krasilich
        skip_cleanup: true
        upload-dir: GmodDotNetBuilds/Osx/$TRAVIS_BRANCH
        local_dir: files_to_publish
        acl: public_read
        on:
          all_branches: true
        endpoint: https://fra1.digitaloceanspaces.com

    - language: minimal
      stage: build
      name: Lua assembler
      script:
        - mkdir folder_to_deploy
        - cp lua/autorun/clientside/gm_dotnet_client.lua folder_to_deploy
        - cp lua/autorun/serverside/gm_dotnet_server.lua folder_to_deploy
      deploy:
        provider: s3
        access_key_id: $SPACE_ID
        secret_access_key: $SPACE_KEY
        bucket: gleb-krasilich
        skip_cleanup: true
        upload-dir: GmodDotNetBuilds/Lua/$TRAVIS_BRANCH/$TRAVIS_COMMIT
        local_dir: folder_to_deploy
        acl: public_read
        on:
          all_branches: true
        endpoint: https://fra1.digitaloceanspaces.com

    - language: minimal
      stage: tests
      dist: bionic
      name: Linux tester
      script:
        - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo add-apt-repository universe
        - sudo apt-get update
        - sudo apt-get install apt-transport-https
        - sudo apt-get update
        - sudo apt-get install dotnet-sdk-3.1
        - dotnet publish gm_dotnet_managed/Tests/Tests.csproj -c Release
        - sudo apt-get install lib32gcc1
        - wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        - tar -xvzf steamcmd_linux.tar.gz
        - rm -rfv steamcmd_linux.tar.gz
        - ./steamcmd.sh +login anonymous +force_install_dir gmod "+app_update 4020 -beta x86-64 validate" +quit
        - mkdir gmod/garrysmod/lua/bin
        - mkdir gmod/garrysmod/lua/bin/Modules
        - mkdir gmod/garrysmod/lua/bin/Modules/Tests
        - cp gm_dotnet_managed/Tests/bin/Release/netcoreapp3.1/publish/* gmod/garrysmod/lua/bin/Modules/Tests
        - cd gmod/garrysmod/lua/autorun/server
        - wget  https://gleb-krasilich.fra1.digitaloceanspaces.com/GmodDotNetBuilds/Lua/$TRAVIS_BRANCH/$TRAVIS_COMMIT/gm_dotnet_server.lua
        - cd ../../../../..
        - cd gmod/garrysmod/lua/bin
        - wget  https://gleb-krasilich.fra1.digitaloceanspaces.com/GmodDotNetBuilds/Linux/$TRAVIS_BRANCH/$TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz
        - tar -xvzf $TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz
        - rm -rfv $TRAVIS_BRANCH-$TRAVIS_COMMIT.tar.gz
        - cd ../../../..
        - cd gmod
        - dir
        - ./srcds_run_x64 -game garrysmod -systemtest || true
        - cd ..
        - mv gmod/tests-success.txt gmod/tests.txt
        - echo "Tests log:"
        - cat gmod/tests-log.txt
      after_success:
        - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        - sudo apt-get install -y nodejs
        - cd node
        - npm update
        - node discord-linux-success.js $WEBHOOK_URL $TRAVIS_BRANCH $TRAVIS_COMMIT "$TRAVIS_COMMIT_MESSAGE"
      after_failure:
        - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        - sudo apt-get install -y nodejs
        - cd node
        - npm update
        - node discord-linux-fail.js $WEBHOOK_URL $TRAVIS_BRANCH $TRAVIS_COMMIT "$TRAVIS_COMMIT_MESSAGE"

    - language: cpp
      stage: tests
      os: windows
      name: Windows tester
      script:
        - curl https://dotnetwebsite.azurewebsites.net/download/dotnet-core/scripts/v1/dotnet-install.ps1 -O -L
        - mkdir ./netcore
        - powershell -Command Set-ExecutionPolicy -Scope CurrentUser Unrestricted
        - powershell -File ./dotnet-install.ps1 -Version 3.1.101 -InstallDir ./netcore
        - ./netcore/dotnet.exe publish gm_dotnet_managed/Tests/Tests.csproj -c Release
        - curl https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip -O -L
        - 7z x -tzip steamcmd.zip
        - ./steamcmd.exe +login anonymous +force_install_dir gmod "+app_update 4020 -beta x86-64 validate" +quit || true
        - mkdir gmod/garrysmod/lua/bin
        - mkdir gmod/garrysmod/lua/bin/Modules
        - mkdir gmod/garrysmod/lua/bin/Modules/Tests
        - cp gm_dotnet_managed/Tests/bin/Release/netcoreapp3.1/publish/* gmod/garrysmod/lua/bin/Modules/Tests
        - cd gmod/garrysmod/lua/autorun/server
        - curl  https://gleb-krasilich.fra1.digitaloceanspaces.com/GmodDotNetBuilds/Lua/$TRAVIS_BRANCH/$TRAVIS_COMMIT/gm_dotnet_server.lua -O -L
        - cd ../../../../..
        - cd gmod/garrysmod/lua/bin
        - curl  https://gleb-krasilich.fra1.digitaloceanspaces.com/GmodDotNetBuilds/Windows/$TRAVIS_BRANCH/$TRAVIS_BRANCH-$TRAVIS_COMMIT.zip -O -L
        - 7z x -tzip $TRAVIS_BRANCH-$TRAVIS_COMMIT.zip
        - rm -rfv $TRAVIS_BRANCH-$TRAVIS_COMMIT.zip
        - cd ../../../..
        - powershell -Command './gmod/srcds_win64.exe -console -systemtest -game "garrysmod" +exec "server.cfg" +gamemode sandbox +map gm_construct +maxplayers 16'
        - sleep 50
        - mv gmod/tests-success.txt gmod/tests.txt
        - echo "Tests log:"
        - cat gmod/tests-log.txt
      after_success:
        - choco install nodejs.install
        - cd node
        - /c/Program\ Files/nodejs/npm.cmd update
        - /c/Program\ Files/nodejs/node.exe discord-windows-success.js $WEBHOOK_URL $TRAVIS_BRANCH $TRAVIS_COMMIT "$TRAVIS_COMMIT_MESSAGE"
      after_failure:
        - choco install nodejs.install
        - cd node
        - /c/Program\ Files/nodejs/npm.cmd update
        - /c/Program\ Files/nodejs/node.exe discord-windows-fail.js $WEBHOOK_URL $TRAVIS_BRANCH $TRAVIS_COMMIT "$TRAVIS_COMMIT_MESSAGE"

    - language: node_js
      node_js:
        - 12
      stage: notification
      name: Discord notifier
      script:
        - cd node
        - npm update
        - node discord.js $WEBHOOK_URL $TRAVIS_BRANCH $TRAVIS_COMMIT "$TRAVIS_COMMIT_MESSAGE"
