name: CI

on: [push, pull_request]

jobs:
 linux-build:

   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.101'

    - name: Install CMake
      run: sudo apt-get install cmake

    - name: Build Managed part
      run: dotnet publish -c Release
      working-directory: ./gm_dotnet_managed/

    - name: Build Native part
      run: |
           mkdir cmake_build
           cd cmake_build
           cmake ../gm_dotnet_native
           make

    - name: Copy build artifacts
      run: |
           mkdir build
           mkdir build/gmodnet
           mkdir build/gmodnet/API
           cp cmake_build/*.dll build
           cp -a -v gm_dotnet_managed/GmodNET/bin/Release/netcoreapp3.1/publish/. build/gmodnet
           cp gm_dotnet_managed/GmodNET.API/bin/Release/netcoreapp3.1/GmodNET.API.dll build/gmodnet/API
           find build/gmodnet/*.exe | xargs rm -f -v
           rm -f -v build/gmodnet/GmodNET
           rm -f -v build/gmodnet/web.config
           cd build
           mkdir dotnet
           cd dotnet
           wget https://download.visualstudio.microsoft.com/download/pr/deeee432-fd3c-4dbc-bc06-cbf166cbcfb7/04747ae7a0ea63e01b6f932cccdcf837/aspnetcore-runtime-3.1.1-linux-x64.tar.gz
           tar xvf aspnetcore-runtime-3.1.1-linux-x64.tar.gz
           rm -f -v aspnetcore-runtime-3.1.1-linux-x64.tar.gz
           cd ..
           cd ..
           cp LICENSE build
           cp NOTICE build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Linux-Raw-Build
        path: ./build

    - name: Download Steam and Install Garry's Mod Dedicated Server
      run: |
           sudo apt-get install lib32gcc1
           wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
           tar -xvzf steamcmd_linux.tar.gz
           rm -rfv steamcmd_linux.tar.gz
           ./steamcmd.sh +login anonymous +force_install_dir gmod "+app_update 4020 -beta x86-64 validate" +quit

    - name: Prepare test run
      run: |
           mkdir gmod/garrysmod/lua/bin
           mkdir gmod/garrysmod/lua/bin/Modules
           mkdir gmod/garrysmod/lua/bin/Modules/Tests
           cp -a gm_dotnet_managed/Tests/bin/Release/netcoreapp3.1/publish/. gmod/garrysmod/lua/bin/Modules/Tests
           cp -a build/. gmod/garrysmod/lua/bin
           cp lua/autorun/serverside/gm_dotnet_server.lua gmod/garrysmod/lua/autorun/server

    - name: Run Garry's Mod
      run: ./srcds_run_x64 -game garrysmod -systemtest || true
      working-directory: ./gmod/

    - name: Check if tests were successful
      run: mv gmod/tests-success.tx gmod/tests.txt

    - name: Print test log
      run: cat gmod/tests-log.txt

    - name: Upload test log
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Linux-Test-Log
        path: gmod/tests-log.txt
