name: CI

on: [push, pull_request]

jobs:
 linux-build:

   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
       dotnet-version: '3.1.101'

    - name: Update CMake
      run: sudo apt install cmake
